# List of files
J_SRCS = cs455.overlay.node.Registry.java cs455.overlay.node.MessagingNode.java

#Compiler and loader commands and flags
GCC = javac

all:
	$(GCC) $(J_SRCS)
clean:
	rm *.class
submission:
	tar -cvf Kielman-Daniel-HW5.tar $(J_SRCS) Makefile README.txt